export const GAME_TOGGLE_TURN = 'GAME_TOGGLE_TURN';
export const GAME_FIELD_CHANGED = 'GAME_FIELD_CHANGED';
export const GAME_OVER = 'GAME_OVER';
export const GAME_PLAYER_WIN = 'GAME_PLAYER_WIN';
export const GAME_WINNING_SEQUENCE = 'GAME_WINNING_SEQUENCE';
export const GAME_RESTART = 'GAME_RESTART';
export const GAME_PLAYER1_WIN = 'GAME_PLAYER1_WIN';
export const GAME_PLAYER2_WIN = 'GAME_PLAYER2_WIN';
